app:
  scheme: https
  host: www.store.com

spring:
  jpa:
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/lc
    username: local
    password: local
    platform: postgres
  flyway:
    baseline-on-migrate: true

server:
  error:
    include-message: always


